### PR TITLE
Some more Pandora adjustments

### PR DESCRIPTION
**Pull request by ptitSeb**
Not sure why I have multiple occurence of the commits... The result seems fine.

### CODE REVIEW

**Comment by DanielGibson** [comment]
That's a lot of commits for a few lines of changes, also many duplicates.. maybe squash them together in an interactive rebase?

**Comment by ptitSeb** [comment]
Better now (I used "git rebase -i" and then "git push -f origin master" to be sure. I still have 2 empty commit, but it's much cleaner now).

**Comment by icculus** [comment]
I'm going to resolve and merge this soon. Just didn't want you to think it's been forgotten!

**Comment by ptitSeb** [comment]
Thanks.
If it's too messy tell me and I'll try to redo it completely.

**Comment by ptitSeb** [comment]
Hi @rcgordon , the pull request is a bit better now.

**Comment by icculus** [comment]
Ok, I'm hitting the button!!

**Pull request merged**
