### PR TITLE
Update README.md to include Linux

### PR DESCRIPTION
**Pull request by yamgent**
A guide to help people who are interested in compiling the game on Linux.

### CODE REVIEW

**Comment by comicfans** [comment]
suggest add following comments in linux copy file section:

since application detect the 'realpath' for executable, soft link (ln -s ) main executable will not work.

**Comment by icculus** [comment]
@comicfans, we should probably fix that in the code (I assume the realpath() is there to help find the base directory of the game and we don't _really_ care where the binary is, right?).

**Comment by comicfans** [comment]
UnixFileSystem.cpp:80 use SDL_GetBasePath() to detect executable path, and SDL uses
readline (/proc/pid/exe) to get executable path(for linux) .  this ignore soft link.

under linux argv[0] may help but not always .

**Comment by clort81** [comment]
Hi, thanks for the work.  I'd like to make some suggestions to make it work better under linux.

1) Player.ecl exists nowhere on the filesystem.   When the executeable does not find a required data file such as 1_00.gro, it would be helpful to report the name and path of the not-found data file to stderr. .. Instead of the filename sought in the .gro archive.

2) It would be helpful to store and read the game-data-path to/from a configuration file. Games under linux commonly store game paths to a configuration file.  This would be conventionally located in ~/.config/serious-engine or similar.
For portability, no spaces are allowed in *nix directory or file names. Best to use alphanumeric ascii.

3) The build for ssam-tfe fails to build EntitiesMP, but the binary ssam-tfe requires EntitiesMP.  It would be helpful to fix the cmake config to build all required libraries for ssam-tfe.  I was able to work-around this by building ssam first.

Cheers

**Pull request merged**
