### PR TITLE
Fix crashes from this!=NULL removal

### LINKED ISSUE #55: this can be NULL - segmentation fault
I get a segmentation fault with the latest commits.

The assertion for (this != NULL) fails at [Sources/Engine/Base/Anim.cpp:182](https://github.com/DanielGibson/Serious-Engine/blob/5badefaf900165feb7196ee78343ceb5ba3d3a4a/Sources/Engine/Base/Anim.cpp#L182). Ignoring this assertion, the code will proceed to crash.

[lldb_log.txt](https://github.com/rcgordon/Serious-Engine/files/289143/lldb_log.txt)

I looked at the commit that made the changes to this portion (5badefa). The compiler does not guard against function calls for NULL "objects" (the function executes anyway on inexistent objects). Therefore, even though the compiler is correct that 'this' pointer cannot be null in well-defined C++ code, the assumption that the code is well-defined in the first place is faulty.

I propose 2 different possible solutions:
1. Either revert commit 5badefa, or
2. Add a if statement to all affected method calls so that it checks that the object is not NULL first before calling its methods. I.e.

Before

```
// will call even if abc is NULL
abc->CallFunction();
```

After

```
// now no longer calls when abc is NULL
if (abc != NULL)
    abc->CallFunction();
```

The second solution is probably "proper" C++.

Note: I looked through the rest of the changes in the commit and some portions will require more work than adding one if statement. (E.g. `CConsole::GetBufferSize()` requires the value of 1 to be returned if `this == NULL`)

### PR DESCRIPTION
**Pull request by DanielGibson**
mostly checks before calling AddReference()/RemReference() so far.

this should fix #55 

I haven't experienced any further crashes, but I only started the first level and played 2 minutes, so there may be more.

### CODE REVIEW

**Comment by DanielGibson** [comment]
and now I've also added a fix for the ModExt.txt vs ModEXT.txt problem.

**Comment by DanielGibson** [comment]
@rcgordon  As the game segfaults at startup without these changes, can you merge this?

**Comment by icculus** [comment]
Sorry, I was busy elsewhere and not paying attention. Merging now!!

**Comment by DanielGibson** [comment]
Thanks a lot! :-)

**Pull request merged**
