### PR TITLE
Auto linking SDL2 libraries

### PR DESCRIPTION
**Pull request by ericwomer**
FindSDL2.cmake: Added module to help find system libraries for SDL2
CMakeLists.txt: Modified to link system wide SDL2 libraries and link to
    system wide headers
SplashScreen.cpp: commented out as its post SDL2.0.4 >> SDL_WINDOW_SKIP_TASKBAR

### CODE REVIEW

**Comment by icculus** [comment]
CC @ptitSeb, I'm moving the SDL2 work over to master, please make sure we didn't destroy the Pandora build.

(I have no idea if GitHub will actually notify users if I do that, let's see what happens.)

**Comment by ptitSeb** [comment]
I'll test soon.

**Comment by ptitSeb** [comment]
It works on my side with SDL2 (and using multi-threading too, I can have a Pull Request about that).

**Comment by icculus** [comment]
> and using multi-threading too, I can have a Pull Request about that

The reason SINGLE_THREADED was forced on was because in 2001 there were lots of things that didn't work well across threads on Linux, not the least of which was the debugger.  :)

I was probably trying to decide if something was a race condition, and just left it that way. If it works, we can turn multithreading back on. It'll orobably help with the occasional lag spike if nothing else. Send a PR and I'll take it.

**Pull request merged**
